version: 1
task_definition:
  ecs_network_mode: bridge
  task_role_arn: ecsTaskExecutionRole
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 256
    mem_limit: 0.5GB
  services:
    grafana:
      cpu_shares: 256
      mem_limit: 256MB
      secrets:
        - value_from: GF_USER
          name: GF_SECURITY_ADMIN_USER
        - value_from: GF_PWD
          name: GF_SECURITY_ADMIN_PASSWORD
        - value_from: GF_ACCESSK
          name: GF_AWS_grafana_ACCESS_KEY_ID
        - value_from: GF_SECRETK
          name: GF_AWS_grafana_SECRET_ACCESS_KEY